- hostname:
    name: "{{ machine_name }}"
- template:
    src: hosts
    dest: /etc/hosts
- apt:
    upgrade: yes
    update_cache: yes
- apt:
    name: "{{ packages }}"
  vars:
    packages:
    - emacs25-nox
    - vim
    - ruby
    - ansible
- gem:
    name: bundler
- timezone:
    name: Asia/Tokyo
- sysctl:
    name: net.core.somaxconn
    value: 8192
- sysctl:
    name: fs.file-max
    value: 5242880
- sysctl:
    name: net.ipv4.tcp_max_syn_backlog
    value: 8192
- sysctl:
    name: net.core.netdev_max_backlog
    value: 8192
- sysctl:
    name: net.ipv4.tcp_tw_reuse
    value: 1
