- apt:
    name: "{{ packages }}"
  vars:
    packages:
    - php7.2-fpm
    - php7.2-intl
    - php7.2-curl
    - phpunit
  when:
   - ansible_distribution == "Ubuntu"
- apt:
    name: "{{ packages }}"
  vars:
    packages:
    - php7.3-fpm
    - php7.3-intl
    - php7.3-curl
    - phpunit
  when:
   - ansible_distribution == "Debian"
- apt:
    name: composer
