- apt:
    name: "{{ packages }}"
  vars:
    packages:
    - php7.2-fpm
    - php7.2-intl
    - php7.2-curl
    - php7.2-mysql
    - php7.2-sqlite3
    - php-redis
    - phpunit
    - composer
  when:
   - ansible_distribution == "Ubuntu"
- ini_file:
    path: /etc/php/7.2/fpm/php.ini
    section: PHP
    option: max_execution_time
    value: 300
  when:
   - ansible_distribution == "Ubuntu"
- service:
    name: php7.2-fpm
    state: restarted
  when:
   - ansible_distribution == "Ubuntu"
- apt:
    name: "{{ packages }}"
  vars:
    packages:
    - php7.3-fpm
    - php7.3-intl
    - php7.3-curl
    - php7.3-mysql
    - php7.3-sqlite3
    - php-redis
    - phpunit
    - composer
  when:
   - ansible_distribution == "Debian"
- ini_file:
    path: /etc/php/7.3/fpm/php.ini
    section: PHP
    option: max_execution_time
    value: 300
  when:
   - ansible_distribution == "Debian"
- service:
    name: php7.3-fpm
    state: restarted
  when:
   - ansible_distribution == "Debian"
