- apt:
    name: nginx-light
- copy:
    src=default
    dest=/etc/nginx/sites-enabled/default
- service: name=nginx state=reloaded
- file:
    src: /vagrant
    dest: /var/www/smartcare-calendar
    state: link
  when: # when vagrant
   - ansible_distribution == "Debian"
- file: path=/var/www/smartcare-calendar/application state=directory owner=ubuntu group=ubuntu mode=0755
  when: # for capistrano
   - ansible_distribution == "Ubuntu"
- template:
    src: application-env
    dest: /var/www/smartcare-calendar/application/.env
  when: # for capistrano
   - ansible_distribution == "Ubuntu"
